#Retrieve target ChEMBL_ID, target_name, target_type, uniprot_reference and sequences for all protein targets:


PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX cco: <http://rdf.ebi.ac.uk/terms/chembl#>


SELECT ?tar ?title ?tarTyp  ?protSeq ?uniref
WHERE {
  
  ?o cco:hasTarget ?tar.
  ?tar dcterms:title ?title.
  ?tar cco:targetType ?tarTyp.
  FILTER regex(?tarTyp, “protein”, ‘i’ )
  ?tar cco:hasTargetComponent ?tc.
  ?tc cco:hasProteinClassification ?pcl.
   
  ?tc cco:proteinSequence ?protSeq.
  ?tc skos:exactMatch ?em.
?em rdfs:label ?uniref.
 
}