
# able to retrive all labeling data in database.

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?subject ?object ?a ?b

WHERE
{
  ?subject rdfs:label ?object.
  ?subject ?a ?b.
}
